In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
dataset = pd.read_csv('Iris.csv')

In [3]:
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
dataset.shape

(150, 5)

In [ ]:
X = dataset.iloc[:, : 4].values
X

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
y = dataset['species'].values
y

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-1.76990493e+00, -1.16010890e-01, -1.40268827e+00,
        -1.33011609e+00],
       [-9.34668898e-01,  1.70973427e+00, -1.06581851e+00,
        -1.06845391e+00],
       [ 2.58525440e-01, -5.72447180e-01,  5.06240396e-01,
        -2.18051819e-02],
       [ 1.21308091e+00,  1.12207255e-01,  8.99255122e-01,
         1.15567464e+00],
       [-1.05398833e+00, -1.71353791e+00, -2.79789055e-01,
        -2.83467364e-01],
       [ 4.97164307e-01,  7.96861690e-01,  1.01154504e+00,
         1.54816791e+00],
       [ 8.55122608e-01, -3.44229035e-01,  4.50095436e-01,
         1.09025909e-01],
       [ 4.97164307e-01, -5.72447180e-01,  7.30820240e-01,
         3.70688092e-01],
       [-2.18752295e-01, -3.44229035e-01,  2.25515592e-01,
         1.09025909e-01],
       [-1.17330776e+00, -1.48531976e+00, -2.79789055e-01,
        -2.83467364e-01],
       [-2.18752295e-01, -5.72447180e-01,  3.93950475e-01,
         1.09025909e-01],
       [ 1.39206006e-01, -1.16010890e-01,  5.62385357e-01,
      

In [15]:
X_test

array([[-0.33807173, -0.57244718,  0.61853032,  1.02484355],
       [ 0.73580317, -0.11601089,  0.7869652 ,  1.02484355],
       [-1.53126607,  0.11220725, -1.29039835, -1.33011609],
       [-0.33807173, -0.11601089,  0.39395047,  0.37068809],
       [-1.17330776,  0.11220725, -1.29039835, -1.46094719],
       [ 0.01988657, -0.11601089,  0.73082024,  0.76318137],
       [-0.45739116, -1.71353791,  0.11322567,  0.10902591],
       [-0.9346689 ,  1.70973427, -1.23425339, -1.33011609],
       [-1.2926272 ,  0.79686169, -1.23425339, -1.33011609],
       [ 0.13920601, -0.34422904,  0.39395047,  0.37068809],
       [ 0.61648374, -0.80066533,  0.84311016,  0.89401246],
       [-0.5767106 ,  1.48151612, -1.29039835, -1.33011609],
       [ 0.49716431, -1.25710162,  0.67467528,  0.89401246],
       [-0.09943286, -0.80066533,  0.73082024,  0.89401246],
       [ 0.13920601,  0.79686169,  0.39395047,  0.50151918],
       [ 2.16763638, -0.11601089,  1.29226985,  1.41733682],
       [ 1.57103921, -0.

In [17]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [18]:
y_pred = classifier.predict(X_test)
y_pred

array(['virginica', 'virginica', 'setosa', 'versicolor', 'setosa',
       'virginica', 'versicolor', 'setosa', 'setosa', 'versicolor',
       'virginica', 'setosa', 'virginica', 'virginica', 'versicolor',
       'virginica', 'virginica', 'setosa', 'setosa', 'versicolor',
       'versicolor', 'setosa', 'virginica', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'setosa', 'versicolor', 'setosa'],
      dtype='<U10')

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[11,  0,  0],
       [ 0,  8,  2],
       [ 0,  1,  8]])

In [20]:

from sklearn.metrics import accuracy_score
print('Accuracy : ', accuracy_score(y_test, y_pred))
Acuuracy : 1.0


Accuracy :  0.9


In [23]:

df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
df

Real Values Predicted Values
0    virginica        virginica
1    virginica        virginica
2       setosa           setosa
3   versicolor       versicolor
4       setosa           setosa
5    virginica        virginica
6   versicolor       versicolor
7       setosa           setosa
8       setosa           setosa
9   versicolor       versicolor
10   virginica        virginica
11      setosa           setosa
12   virginica        virginica
13   virginica        virginica
14  versicolor       versicolor
15   virginica        virginica
16   virginica        virginica
17      setosa           setosa
18      setosa           setosa
19  versicolor       versicolor
20  versicolor       versicolor
21      setosa           setosa
22  versicolor        virginica
23  versicolor        virginica
24  versicolor       versicolor
25      setosa           setosa
26  versicolor       versicolor
27      setosa           setosa
28   virginica       versicolor
29      setosa           setosa

In [24]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print metrics
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")


Confusion Matrix:
 [[11  0  0]
 [ 0  8  2]
 [ 0  1  8]]
Accuracy: 0.90
Error Rate: 0.10
Precision: 0.90
Recall: 0.90
